remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

url: https://tomcoward.me

locale : "en-GB"
title: "Tom Coward"
name: "Tom Coward"
description: "A personal portfolio site for Tom Coward, a Software Engineer based in Liverpool, UK"
